### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by dillardd** [mpearon/PUB-vsce.parse-CMTraceLogs#3]
Steps:

1. Open folder that contains CM Trace logs (C:\Windows\CCM\Logs)
2. Open file from folder by clicking file
3. Try to change language
4. Try to open file by using right-click menu, no available options.

I cannot see how to use this extension, and there are no instructions on how to do so.

**Comment by mpearon** [comment]
This extension should be marked as being in Preview - but I should probably just remove the listing as I kind of lost interest.

The original idea was to parse via RegEx and display in a webview - but I never really got anywhere with it.
